---
- hosts: tag_Name_MySQL
  remote_user: ubuntu
  gather_facts: no
  become: yes
  become_method: sudo
  connection: ssh
  vars:
    mysql_root_password: mysql

  tasks:
    - name: Install MySQL
      action: yum name={{ item }} state=present
      with_items:
        - mysql-server
        - python-mysqldb
        - libmysqlclient-dev
        - python-mysql.connector
        - python3-mysql.connector

    - name: Start the MySQL service
      action: service name=mysql state=started

    - name: Remove the test database
      mysql_db: name=test state=absent

    - name: Create mysql user for mysql
      mysql_user: user="mysql" host="%" password={{mysql_root_password}} priv=*.*:ALL,GRANT

    - name: Ensure anonymous users are not in the database
      mysql_user: user='' host= state=absent
      with_items:
        - 127.0.0.1
        - ::1
        - localhost

   # - name: Copy .my.cnf file with root password credentials
   #   template: src=templates/.my.cnf dest=/etc/mysql/my.cnf owner=root mode=0600

    - name: Update mysql root password for all root accounts
      mysql_user: name=root host={{item}} password={{mysql_root_password}}
      with_items:
        - 127.0.0.1
        - ::1
        - localhost
...
